package cz.zcu.kiv.server.sqlite;

import cz.zcu.kiv.server.sqlite.Model.Module;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import java.sql.*;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Modules {
    private static Log logger = LogFactory.getLog(Modules.class);

    private String database;

    public static Module addModule(Module module) {
        if(getModuleByName(module.getJarName(),module.getPackageName())==null){
            Connection connection = null;
            PreparedStatement preparedStatement = null;
            try {
                connection = SQLiteDB.getInstance().connect();
                preparedStatement =
                        connection.prepareStatement("INSERT into modules (jarName, packageName, publicJar, author, lastUpdate) VALUES (?,?,?,?,?);",
                                Statement.RETURN_GENERATED_KEYS);

                preparedStatement.setString(1, module.getJarName());
                preparedStatement.setString(2, module.getPackageName());
                preparedStatement.setBoolean(3, module.isPublicJar());
                preparedStatement.setString(4, module.getAuthor());
                Timestamp currentTimestamp = new Timestamp(System.currentTimeMillis());
                preparedStatement.setTimestamp(5,currentTimestamp);

                preparedStatement.executeUpdate();

                ResultSet tableKeys = preparedStatement.getGeneratedKeys();
                tableKeys.next();
                long autoGeneratedID = tableKeys.getLong(1);
                module.setId(autoGeneratedID);
                module.setLastUpdate(new Date(currentTimestamp.getTime()));
                return module;
            }
            catch (SQLException e){
                logger.error(e);
                return null;
            }
            finally {
                if(preparedStatement!=null) {
                    try {
                        preparedStatement.close();
                    } catch (SQLException e1) {
                        logger.error(e1);
                    }
                }
                if(connection!=null){
                    try {
                        connection.close();
                    } catch (SQLException e1) {
                        logger.error(e1);
                    }
                }
            }

        }
        else{
           return null;
        }
    }

    public static Module getModuleByName(String jarName, String packageName ){
        Connection connection = null;
        PreparedStatement preparedStatement = null;
        try {
            connection = SQLiteDB.getInstance().connect();
            preparedStatement =
                    connection.prepareStatement("SELECT * FROM modules WHERE jarName=? AND packageName=?;" );

            preparedStatement.setString(1, jarName);
            preparedStatement.setString(2, packageName);

            ResultSet resultSet = preparedStatement.executeQuery();
            if(resultSet.next()){
                Module module=new Module();
                module.setJarName(resultSet.getString("jarName"));
                module.setPackageName(resultSet.getString("packageName"));
                module.setPublicJar(resultSet.getBoolean("publicJar"));
                module.setAuthor(resultSet.getString("author"));
                module.setId(resultSet.getLong("id"));
                return module;
            }
            else return null;
        }
        catch (SQLException e){
            logger.error(e);
            return null;
        }
        finally {
            if(preparedStatement!=null) {
                try {
                    preparedStatement.close();
                } catch (SQLException e1) {
                    logger.error(e1);
                }
            }
            if(connection!=null){
                try {
                    connection.close();
                } catch (SQLException e1) {
                    logger.error(e1);
                }
            }

        }
    }

    public static List<Module> getModulesByJar(String jarName ){
        Connection connection = null;
        PreparedStatement preparedStatement = null;
        try {
            connection = SQLiteDB.getInstance().connect();
            preparedStatement =
                    connection.prepareStatement("SELECT * FROM modules WHERE jarName=?;" );

            preparedStatement.setString(1, jarName);

            ResultSet resultSet = preparedStatement.executeQuery();
            List<Module>modules=new ArrayList<>();
            while(resultSet.next()){
                Module module=new Module();
                module.setJarName(resultSet.getString("jarName"));
                module.setPackageName(resultSet.getString("packageName"));
                module.setPublicJar(resultSet.getBoolean("publicJar"));
                module.setAuthor(resultSet.getString("author"));
                module.setId(resultSet.getLong("id"));
                modules.add(module);
            }
            return modules.isEmpty()?null:modules;
        }
        catch (SQLException e){
            logger.error(e);
            return null;
        }
        finally {
            if(preparedStatement!=null) {
                try {
                    preparedStatement.close();
                } catch (SQLException e1) {
                    logger.error(e1);
                }
            }
            if(connection!=null){
                try {
                    connection.close();
                } catch (SQLException e1) {
                    logger.error(e1);
                }
            }

        }
    }



    public static Module updateModule(Module module){
        Connection connection = null;
        PreparedStatement preparedStatement = null;
        try {
            connection = SQLiteDB.getInstance().connect();
            preparedStatement =
                    connection.prepareStatement("UPDATE modules SET publicJar=?,author=?,lastUpdate=?  WHERE id=?;" );

            preparedStatement.setBoolean(1, module.isPublicJar());
            preparedStatement.setString(2, module.getAuthor());
            Timestamp currentTimestamp = new Timestamp(System.currentTimeMillis());
            preparedStatement.setTimestamp(3,currentTimestamp);
            preparedStatement.setLong(4, module.getId());


            int updateRows = preparedStatement.executeUpdate();
            if(updateRows!=0)
                return module;
            return null;
        }
        catch (SQLException e){
            logger.error(e);
            return null;
        }
        finally {
            if(preparedStatement!=null) {
                try {
                    preparedStatement.close();
                } catch (SQLException e1) {
                    logger.error(e1);
                }
            }
            if(connection!=null){
                try {
                    connection.close();
                } catch (SQLException e1) {
                    logger.error(e1);
                }
            }

        }
    }

    public static List<Module> getModulesForUser(String userEmail ){
        Connection connection = null;
        PreparedStatement preparedStatement = null;
        try {
            connection = SQLiteDB.getInstance().connect();
            preparedStatement =
                    connection.prepareStatement("SELECT * FROM modules WHERE publicJar=true;" );

           // preparedStatement.setString(1, userEmail);

            ResultSet resultSet = preparedStatement.executeQuery();
            List<Module>modules=new ArrayList<>();
            while(resultSet.next()){
                Module module=new Module();
                module.setJarName(resultSet.getString("jarName"));
                module.setPackageName(resultSet.getString("packageName"));
                module.setPublicJar(resultSet.getBoolean("publicJar"));
                module.setAuthor(resultSet.getString("author"));
                module.setId(resultSet.getLong("id"));
                modules.add(module);
            }
            return modules.isEmpty()?null:modules;
        }
        catch (SQLException e){
            logger.error(e);
            return null;
        }
        finally {
            if(preparedStatement!=null) {
                try {
                    preparedStatement.close();
                } catch (SQLException e1) {
                    logger.error(e1);
                }
            }
            if(connection!=null){
                try {
                    connection.close();
                } catch (SQLException e1) {
                    logger.error(e1);
                }
            }

        }
    }
}
