package cz.zcu.kiv.server.sqlite;

import cz.zcu.kiv.server.sqlite.Model.User;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import java.sql.*;

public class Users {
    private static Log logger = LogFactory.getLog(Users.class);

    public static User addUser(User user) throws SQLException, UserAlreadyExistsException {
        try {
            getUserByEmail(user.getEmail());
            //The user already exists in DB
            throw new UserAlreadyExistsException(user.getEmail());

        } catch (UserDoesNotExistException e) {
            Connection connection = null;
            PreparedStatement preparedStatement = null;
            try {
                connection = SQLiteDB.getInstance().connect();
                preparedStatement =
                        connection.prepareStatement("INSERT into users (email, password, username, token) VALUES (?,?,?,?);",
                                Statement.RETURN_GENERATED_KEYS);

                preparedStatement.setString(1, user.getEmail());
                preparedStatement.setString(2, user.getPassword());
                preparedStatement.setString(3, user.getUsername());
                preparedStatement.setString(4, user.getToken());

                preparedStatement.executeUpdate();

                ResultSet tableKeys = preparedStatement.getGeneratedKeys();
                tableKeys.next();
                long autoGeneratedID = tableKeys.getLong(1);
                user.setId(autoGeneratedID);
                return user;
            }
            finally {
                if(preparedStatement!=null) {
                    try {
                        preparedStatement.close();
                    } catch (SQLException e1) {
                        logger.error(e1);
                    }
                }
                if(connection!=null){
                    try {
                        connection.close();
                    } catch (SQLException e1) {
                        logger.error(e1);
                    }
                }
            }
        }
    }

    public static User getUserByEmail(String email) throws SQLException, UserDoesNotExistException {
        Connection connection = null;
        PreparedStatement preparedStatement = null;
        try {
            connection = SQLiteDB.getInstance().connect();
            preparedStatement =
                    connection.prepareStatement("SELECT * FROM users WHERE email=?;" );

            preparedStatement.setString(1, email);

            ResultSet resultSet = preparedStatement.executeQuery();
            if(resultSet.next()){
                User user=new User();
                user.setEmail(resultSet.getString("email"));
                user.setPassword(resultSet.getString("password"));
                user.setUsername(resultSet.getString("username"));
                user.setToken(resultSet.getString("token"));
                user.setId(resultSet.getLong("id"));
                return user;
            }
            else throw new UserDoesNotExistException(email);
        }
        finally {
            if(preparedStatement!=null) {
                try {
                    preparedStatement.close();
                } catch (SQLException e1) {
                    logger.error(e1);
                }
            }
            if(connection!=null){
                try {
                    connection.close();
                } catch (SQLException e1) {
                    logger.error(e1);
                }
            }

        }
    }

    public static User updateUser(User user) throws SQLException, UserDoesNotExistException {
        //Check if user exists
        getUserByEmail(user.getEmail());
        {
            Connection connection = null;
            PreparedStatement preparedStatement = null;
            try {
                connection = SQLiteDB.getInstance().connect();
                preparedStatement =
                        connection.prepareStatement("UPDATE users SET password=?, token=? WHERE id=?;",
                                Statement.RETURN_GENERATED_KEYS);

                preparedStatement.setString(1, user.getPassword());
                preparedStatement.setString(2, user.getToken());
                preparedStatement.setLong(3, user.getId());

                preparedStatement.executeUpdate();
                return user;
            }
            finally {
                if(preparedStatement!=null) {
                    try {
                        preparedStatement.close();
                    } catch (SQLException e1) {
                        logger.error(e1);
                    }
                }
                if(connection!=null){
                    try {
                        connection.close();
                    } catch (SQLException e1) {
                        logger.error(e1);
                    }
                }
            }

        }
    }

    public static boolean checkAuthorized(String email, String token) throws SQLException{
        try {
            User user=getUserByEmail(email);
            if(!user.getToken().equals(token))
                return false;
        } catch (UserDoesNotExistException e) {
            logger.error(e);
            return false;
        }
        return true;
    }
}
